In [ ]:
print("hello")

hello


In [ ]:
# Importing numpy

import numpy as np

In [ ]:
list = [10,20,30,40]
print(list)

[20, 30, 40, 40]


In [ ]:
arr = np.array([20, 30, 40, 50])
print(arr)

[20 30 40 50]


In [ ]:
# cheaking version of numpy

print(np.__version__)

1.26.4


In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr2 = np.array((1,2,3,4,5))
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0 darray

arr3 = np.array([34])
print(arr3)

[34]


In [ ]:
# 1 darray

arr4 = np.array([34,45,56])
print(arr4)

[34 45 56]


In [ ]:
# 2 darray

arr5 = np.array([[34,45,56], [57,78,79]])
print(arr5)

[[34 45 56]
 [57 78 79]]


In [ ]:
# 3darray

arr6 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr6)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# To cheak dimensionality

print(arr6.ndim)

3


In [ ]:
# Accessing elements 1D

arr = np.array([20,30,40,50,60])
print(arr[3])

50


In [ ]:
#Accessing 2D array elements

arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
#Accessing 2D array elements with -ve indexing

arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, -1])

2nd element on 1st row:  5


In [ ]:
# Accessing elements using slicing

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:11:2])

[ 2  4  6  8 10]


In [ ]:
# Accessing elements using -ve slicing

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[-3:-1])
print(arr[5:9:2])

[8 9]
[6 8]


In [ ]:
# cheaking datatype

arr = np.array([1,2,3.0,4.6,5.8,6,7,8])
print(arr.dtype)

float64


In [ ]:
# Conversion of datatype

arr = np.array([1,2,3.0,4.6,5.8,6,7,8])
print(arr.dtype)
print(arr.astype(int))

float64
[1 2 3 4 5 6 7 8]


In [ ]:
# Cheaking shape of an array ((a,b) where a shows rows and b represents elements in column)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]]) 
print(arr.shape) 

print(arr.size)

(2, 4)
8


In [ ]:
# Reshaping array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(4, 3) 
print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Iterating elements

arr = np.array([1, 2, 3]) 
for x in arr: 
     print(x) 

1
2
3


In [ ]:
# Joining array

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.concatenate((arr1,arr2))
print(newarr)

[1 2 3 4 5 6]


In [ ]:
# Splitting array

arr = np.array([1, 2, 3, 4, 5, 6]) 
newarr = np.array_split(arr, 3) 
print(newarr) 

[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# Searching array(It returns with index)

arr = np.array([1,2,3,4,5,6,7,8])
x=np.where(arr==8)
print(x)

(array([7], dtype=int64),)


In [ ]:
# Sorting array

arr1 = np.array([3,6,2,7,9,2,0])         # for ascending order
print(np.sort(arr1))

arr2 = np.array([3,7,1,0,9,7])          # for Descending order
print(np.sort(arr2)[::-1])

[0 2 2 3 6 7 9]
[9 7 7 3 1 0]


In [ ]:
# Filtering array

arr = np.array([41, 42, 43, 44]) 
x = [True, False, True, False] 
newarr = arr[x] 
print(newarr) 

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])                                 # append = adding elements in new array at the end

# Create an empty list                                           # Insert = adding elements at specific index of an array
filter_arr = [] 

# go through each element in arr 
for element in arr: 
# if the element is higher than 42, set the value to True, otherwise False: 
     if element > 42: 
          filter_arr.append(True) 
     else: 
          filter_arr.append(False)

newarr = arr[filter_arr] 

print(filter_arr)

print(newarr) 

[False, False, True, True]
[43 44]


In [ ]:
# Adding and Removing elements

arr = np.array([20,30,40])
print(np.append(arr,[50,60]))

print(np.insert(arr,2,[90,80]))         # (arr,index,element)

print(np.delete(arr,[1]))

[20 30 40 50 60]
[20 30 90 80 40]
[20 40]


In [ ]:
# Aggregating functions

a = np.array([20,30,40,50])

# sum of all elements
print(np.sum(a))

# Minimum
print(np.min(a))

# maximum
print(np.max(a))

# Cumulative sum
print(np.cumsum(a))

140
20
50
[ 20  50  90 140]


In [ ]:
# Statistical Functions

import statistics as stats

food_price = [20,30,40,50,60,70,20,30,20,30]
a = np.array(food_price)

# Mean 
print(np.mean(a))

# Median 
print(np.median(a))

# Mode
print(stats.mode(a))

37.0
30.0
20
